/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "LED_3.h"
#include "LED_3_aliases.h"
#include "LED_4.h"
#include "LED_4_aliases.h"
#include "SENSOR_1.h"
#include "SENSOR_1_I2C.h"
#include "SENSOR_1_PINS.h"
#include "SENSOR_1_I2C_PVT.h"
#include "SENSOR_1_PVT.h"
#include "SENSOR_1_BOOT.h"
#include "SENSOR_2.h"
#include "SENSOR_2_I2C.h"
#include "SENSOR_2_PINS.h"
#include "SENSOR_2_I2C_PVT.h"
#include "SENSOR_2_PVT.h"
#include "SENSOR_2_BOOT.h"
#include "SENSOR_3.h"
#include "SENSOR_3_I2C.h"
#include "SENSOR_3_PINS.h"
#include "SENSOR_3_I2C_PVT.h"
#include "SENSOR_3_PVT.h"
#include "SENSOR_3_BOOT.h"
#include "SENSOR_4.h"
#include "SENSOR_4_I2C.h"
#include "SENSOR_4_PINS.h"
#include "SENSOR_4_I2C_PVT.h"
#include "SENSOR_4_PVT.h"
#include "SENSOR_4_BOOT.h"
#include "MOTOR.h"
#include "RX_2.h"
#include "RX_2_aliases.h"
#include "TX_2.h"
#include "TX_2_aliases.h"
#include "CAN.h"
#include "SENSOR_1_SCBCLK.h"
#include "SENSOR_1_sda.h"
#include "SENSOR_1_sda_aliases.h"
#include "SENSOR_1_scl.h"
#include "SENSOR_1_scl_aliases.h"
#include "SENSOR_1_SCB_IRQ.h"
#include "SENSOR_2_SCBCLK.h"
#include "SENSOR_2_sda.h"
#include "SENSOR_2_sda_aliases.h"
#include "SENSOR_2_scl.h"
#include "SENSOR_2_scl_aliases.h"
#include "SENSOR_2_SCB_IRQ.h"
#include "SENSOR_3_SCBCLK.h"
#include "SENSOR_3_sda.h"
#include "SENSOR_3_sda_aliases.h"
#include "SENSOR_3_scl.h"
#include "SENSOR_3_scl_aliases.h"
#include "SENSOR_3_SCB_IRQ.h"
#include "SENSOR_4_SCBCLK.h"
#include "SENSOR_4_sda.h"
#include "SENSOR_4_sda_aliases.h"
#include "SENSOR_4_scl.h"
#include "SENSOR_4_scl_aliases.h"
#include "SENSOR_4_SCB_IRQ.h"
#include "MOTOR_IntClock.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

